### ISSUE TITLE
Hi there

### ISSUE THREAD

**Issue by DiogoJorge1401** [pauloavila88/algoz#1]
Hey how are you, I'm strunggling to use the zapimoveis.com.br api let get in touch?

**Comment by franciscomvargas** [comment]
Hello Diogo, I'm the developer of Algoz. Perhaps I can give you more insight on [zapimoveis](https://www.zapimoveis.com.br/) API

**Comment by DiogoJorge1401** [comment]
Do you have discord?
My id: suegoidkun, otherwise
My linkedin: https://www.linkedin.com/in/diogo-jorge-br/

**Comment by franciscomvargas** [comment]
Please check your linkedin connection requests
